SET TIMING ON
SET APPINFO ON

PROMPT Enter schema name
DEFINE SCHEMA_NAME = &&1
DEFINE TABLESPACE_NAME = '&&SCHEMA_NAME._DATA'

SPOOL DROP_LOG.LOG
SET SERVEROUTPUT ON

PROMPT ---
PROMPT Executing drop_schema.sql
PROMPT ---

@drop_schema.sql &&SCHEMA_NAME

PROMPT ---
PROMPT Executing drop_tablespace.sql
PROMPT ---

@drop_tablespace.sql &&TABLESPACE_NAME

SET SERVEROUTPUT OFF
SPOOL OFF

UNDEFINE SCHEMA_NAME;
UNDEFINE TABLESPACE_NAME;