DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TABLESPACE_NAME = '&&SCHEMA_NAME._DATA'
DEFINE DATA_TABLESPACE_DBF_FILE = '&&DATA_TABLESPACE_NAME..dbf'

CREATE TABLESPACE &&DATA_TABLESPACE_NAME
	DATAFILE '&&DATA_TABLESPACE_DBF_FILE' SIZE 5M AUTOEXTEND ON NEXT 10M MAXSIZE 2G;
	
UNDEFINE DATA_TABLESPACE_NAME;
UNDEFINE DATA_TABLESPACE_DBF_FILE;