DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TABLESPACE_NAME = '&&SCHEMA_NAME._DATA'
DEFINE INDEX_TABLESPACE_NAME = '&&SCHEMA_NAME._IDX'

-- PKs

ALTER TABLE Playlist ADD CONSTRAINT PK_Playlist PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE Composition ADD CONSTRAINT PK_Composition PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE UserT ADD CONSTRAINT PK_User PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE UsersCompositions ADD CONSTRAINT PK_UsersCompositions PRIMARY KEY (User_ID,Composition_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE PlaylistSongs ADD CONSTRAINT PK_PlaylistSongs PRIMARY KEY (Playlist_ID,Song_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE Album ADD CONSTRAINT PK_Album PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE AlbumSongs ADD CONSTRAINT PK_AlbumSongs PRIMARY KEY (Composition_ID,Album_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE SongsLikes ADD CONSTRAINT PK_SongsLikes PRIMARY KEY (User_ID,Composition_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE AlbumsLikes ADD CONSTRAINT PK_AlbumsLikes PRIMARY KEY (Album_ID,User_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE Style ADD CONSTRAINT PK_Style PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE Preferences ADD CONSTRAINT PK_Preferences PRIMARY KEY (User_ID,Style_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE Subscriptions ADD CONSTRAINT PK_Subscriptions PRIMARY KEY (User_ID,Subscribed_to) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE CompositionReviews ADD CONSTRAINT PK_CompositionReviews PRIMARY KEY (User_ID,Composition_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE AlbumReviews ADD CONSTRAINT PK_AlbumReviews PRIMARY KEY (User_ID,Album_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

ALTER TABLE ListeningHistory ADD CONSTRAINT PK_ListeningHistory PRIMARY KEY (User_ID,Composition_ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE_NAME;

-- Indexes

CREATE INDEX User_ListeningTo_IDX ON UserT (Listening_to) TABLESPACE &&INDEX_TABLESPACE_NAME;

CREATE INDEX Album_Owner_IDX ON Album (Owner_ID) TABLESPACE &&INDEX_TABLESPACE_NAME;

CREATE INDEX Album_Style_IDX ON Album (Style_ID) TABLESPACE &&INDEX_TABLESPACE_NAME;

CREATE INDEX Composition_Style_IDX ON Composition (Style_ID) TABLESPACE &&INDEX_TABLESPACE_NAME;

CREATE INDEX Composition_Owner_IDX ON Composition (Owner_ID) TABLESPACE &&INDEX_TABLESPACE_NAME;

-- FKs

ALTER TABLE Composition ADD CONSTRAINT Composition_Owner_UserID FOREIGN KEY (Owner_ID) REFERENCES UserT (ID);

ALTER TABLE PlaylistSongs ADD CONSTRAINT PlaylistSongs_PlaylistID FOREIGN KEY (Playlist_ID) REFERENCES Playlist (ID);

ALTER TABLE PlaylistSongs ADD CONSTRAINT PlaylistSongs_SongID FOREIGN KEY (Song_ID) REFERENCES Composition (ID);

ALTER TABLE AlbumSongs ADD CONSTRAINT AlbumSongs_SongID FOREIGN KEY (Composition_ID) REFERENCES Composition (ID);

ALTER TABLE AlbumSongs ADD CONSTRAINT AlbumSongs_AlbumID FOREIGN KEY (Album_ID) REFERENCES Album (ID);

ALTER TABLE SongsLikes ADD CONSTRAINT SongsLikes_UserID FOREIGN KEY (User_ID) REFERENCES UserT (ID);

ALTER TABLE SongsLikes ADD CONSTRAINT SongsLikes_SongID FOREIGN KEY (Composition_ID) REFERENCES Composition (ID);

ALTER TABLE AlbumsLikes ADD CONSTRAINT AlbumsLikes_AlbumID FOREIGN KEY (Album_ID) REFERENCES Album (ID);

ALTER TABLE AlbumsLikes ADD CONSTRAINT AlbumsLikes_UserID FOREIGN KEY (User_ID) REFERENCES UserT (ID);

ALTER TABLE Composition ADD CONSTRAINT FK_Composition_StyleID FOREIGN KEY (Style_ID) REFERENCES Style (ID);

ALTER TABLE Album ADD CONSTRAINT FK_Album_StyleID FOREIGN KEY (Style_ID) REFERENCES Style (ID);

ALTER TABLE Preferences ADD CONSTRAINT Preferences_UserID FOREIGN KEY (User_ID) REFERENCES UserT (ID);

ALTER TABLE Preferences ADD CONSTRAINT Preferences_StyleID FOREIGN KEY (Style_ID) REFERENCES Style (ID);

ALTER TABLE Subscriptions ADD CONSTRAINT Subscriptions_UserID FOREIGN KEY (User_ID) REFERENCES UserT (ID);

ALTER TABLE Subscriptions ADD CONSTRAINT Subscriptions_SubscribedTo FOREIGN KEY (Subscribed_to) REFERENCES UserT (ID);

ALTER TABLE Album ADD CONSTRAINT Album_Owner_UserID FOREIGN KEY (Owner_ID) REFERENCES UserT (ID);

ALTER TABLE CompositionReviews ADD CONSTRAINT CompositionReviews_UserID FOREIGN KEY (User_ID) REFERENCES UserT (ID);

ALTER TABLE CompositionReviews ADD CONSTRAINT CompositionReviews_SongID FOREIGN KEY (Composition_ID) REFERENCES Composition (ID);

ALTER TABLE AlbumReviews ADD CONSTRAINT AlbumReviews_UserID FOREIGN KEY (User_ID) REFERENCES UserT (ID);

ALTER TABLE AlbumReviews ADD CONSTRAINT AlbumReviews_AlbumID FOREIGN KEY (Album_ID) REFERENCES Album (ID);

ALTER TABLE ListeningHistory ADD CONSTRAINT ListeningHistory_UserID FOREIGN KEY (User_ID) REFERENCES UserT (ID);

ALTER TABLE ListeningHistory ADD CONSTRAINT ListeningHistory_SongID FOREIGN KEY (Composition_ID) REFERENCES Composition (ID);

ALTER TABLE UserT ADD CONSTRAINT User_ListeningTo_SongID FOREIGN KEY (Listening_to) REFERENCES Composition (ID);

UNDEFINE DATA_TABLESPACE_NAME;
UNDEFINE INDEX_TABLESPACE_NAME;

