DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TABLESPACE_NAME = '&&SCHEMA_NAME._DATA'

CREATE TABLE Style(
  ID Number GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
  Style Varchar2(30 ) NOT NULL,
  Rating Float
) TABLESPACE &&DATA_TABLESPACE_NAME;

COMMENT ON COLUMN Style.ID IS 'Style''s ID (PK)';
COMMENT ON COLUMN Style.Style IS 'Style''s name';
COMMENT ON COLUMN Style.Rating IS 'Style''s rating';