DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TABLESPACE_NAME = '&&SCHEMA_NAME._DATA'

ALTER TABLE ALBUM MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE COMPOSITION MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE PLAYLIST MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE USERT MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE UsersCompositions MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE PlaylistSongs MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE AlbumSongs MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE SongsLikes MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE AlbumsLikes MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE Style MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE Preferences MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE Subscriptions MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE CompositionReviews MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE AlbumReviews MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

ALTER TABLE ListeningHistory MOVE TABLESPACE &&DATA_TABLESPACE_NAME;

UNDEFINE DEFINE DATA_TABLESPACE_NAME;
